[project]
name = "customer-behavior-analaysis"
version = "0.1.0"
author = "Sujal Karbhari"
author-email  = "karbharisujal1@gmail.com"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]
